FROM node:18

WORKDIR /usr/src/app

COPY package*.json ./
# Add build tools for native modules
RUN apt-get update && apt-get install -y python3 make g++

RUN npm install

COPY . .

RUN npm run build

EXPOSE 8080

CMD ["node", "dist/server.js"]
